import type { Metadata } from "next";
import { Rubik, Lato } from "next/font/google";
import "./globals.css";
import { Header } from "@/src/components/header/Header";
import { Footer } from "@/src/components/footer/Footer";

const rubikFont = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
    weight: ["400", "600"],
});

const latoFont = Lato({
    variable: "--font-Lato",
    weight: ["700"],
});

export const metadata: Metadata = {
    title: "Printers | Перевізники Європи",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ua"
            className={`${rubikFont.variable} ${latoFont.variable}`}
        >
            <head>
                <link
                    rel="icon"
                    type="image/png"
                    href="/favicon-96x96.png"
                    sizes="96x96"
                />
                <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
                <link rel="shortcut icon" href="/favicon.ico" />
                <link
                    rel="apple-touch-icon"
                    sizes="180x180"
                    href="/apple-touch-icon.png"
                />
                <link rel="manifest" href="/manifest" />
            </head>
            <body>
                <div className="min-h-screen flex flex-col">
                    <Header />
                    <main className="flex-auto min-h-full">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
